### ISSUE TITLE
modelName is not defined

### ISSUE THREAD

**Issue by Hokimisu** [samuelcardillo/StarCitizen-AI#3]
Failed at creating reply:  ReferenceError: modelName is not defined
    at loadModel (file:///E:/Jeux/StarCitizenAssistant/xvasynth.js:12:15)
    at Module.exportSpeech (file:///E:/Jeux/StarCitizenAssistant/xvasynth.js:39:11)
    at createCompletion (file:///E:/Jeux/StarCitizenAssistant/openai.js:127:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createReply (file:///E:/Jeux/StarCitizenAssistant/index.js:21:20)

**Comment by Hokimisu** [comment]
Apparently resolved with const before modelName variable line 12 like : 

const modelName = ttsParams.model.split(".hg.pt")[0];

**Comment by samuelcardillo** [comment]
modelName was dropped in latest code iteration & new structure should solve any related issue
